# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     
  build:
    runs-on: ubuntu-latest
    # The type of runner that the job will run on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Generate PDF files from .md files
        run: |
          cd $GITHUB_WORKSPACE/PECs/PEC5/parte1/doc/
          pandoc analisis.md -f markdown -t latex -s -o analisis.pdf
